# Generated by Django 3.2.13 on 2022-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220630_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newssettings',
            options={'verbose_name': 'News Settings', 'verbose_name_plural': 'News Settings'},
        ),
        migrations.AlterModelOptions(
            name='newssource',
            options={'verbose_name': 'News Source', 'verbose_name_plural': 'News Sources'},
        ),
    ]
