# Generated by Django 3.2.13 on 2022-06-30 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220630_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssettings',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newssettings',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newssettings',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=125), blank=True, null=True, size=None),
        ),
    ]
